### ISSUE TITLE
beta checklist

### ISSUE THREAD

**Issue by m4chinations** [ksdt/new-website#2]
things to do for beta version of website
- [x] build html views + styles with placeholder content
  - [x] wireframe
    - [x] front page view (raymond)
    - [x] schedule view (tennyson)
    - [x] events view (raymond)
    - [x] generic page view (tennyson) 
    - [x] blog post (tennyson)
    - [x]  DJ view (raymond)
    - [x]  show view (raymond)
    - [x]  podcast / recorded show view (raymond)
    - [x]  the rest
- [ ]  style it
- [ ]  convert to WP theme
  - [x]  separate out into php files
  - [ ] replace placeholder content with proper wp api calls
  - [x] add styles for wordpress classes
  - [ ] import existing wp content
  - [ ] fix any issues with previous wp content
- [x]  build custom components
  - [x] audio visualizer
  - [ ] ajaxifier (ala soundcloud)
- [ ] get feedback
- [ ] resolve feedback issues
- [ ] connect 3rd party services
  - [ ] instagram
  - [ ] facebook
  - [ ] icecast
  - [ ] g cal
  - [x] spinitron
  - [ ] playlist-analysis
  - [ ] podcast server
  - [ ]  twitter
  - [x]  jetpack
  - [x] now playing
  - [ ] backblaze
- [ ] build dj portal plugin where djs can
  - [ ] view listeners
  - [ ] see past show information, analysis statistics, attendence
  - [ ] get links to downloads of past shows
  - [ ] edit show images and dj images and descriptions (avoiding spinitron b/c their image size limits are dumb) 
  - [ ] mark their show as a podcast show and edit podcast information
